### ISSUE TITLE
과제에 필요한 기능 버전 결정

### ISSUE THREAD

**Issue by bye0607** [wqe2209/Mission05_Study1Team#1]
과제에 필요한 기능 중 공통으로 사용할 항목들을 어떻게 할건지 의견을 나눴으면 합니다.
필수 기능 중에 font awesome와 bootstrap 버전을 결정해야 할 것 같은데
이 두가지를 검토해보고 각자 작업할 페이지에 맞춰 의견을 제시해주세요

**Comment by jungenjin** [comment]
http://bootstrapk.com/
https://cdnjs.com/libraries/font-awesome/5.15.4

우선은 수업 때 했던 버전으로 해보는 건 어떨까요??

**Comment by amyprko** [comment]
수업때 했던 버전으로 하는게 저도 좋을것 같아요!

**Comment by wqe2209** [comment]
저도 수업 때 했던 버전으로 하는 것에 찬성합니다!

**Comment by bye0607** [comment]
좋아요!
그리고 cdn방식으로 할지랑..
jquery 버전도 결정해야할 것 같아요

**Comment by bye0607** [comment]
부트스트랩 3.3.2
제이쿼리도 부트스트랩에 적용된 버전을 cdn방식으로 적용합니다.
http://bootstrapk.com/getting-started/#template
font awesome : cdn 방식

**Comment by jungenjin** [comment]
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

이런 식으로 버전을 정하면 되는 건가요??

**Comment by amyprko** [comment]
좋아용 👍👍 알겠습니다
